from pathlib import Path
import time
from llama_cpp import Llama

def run_evolving_history_benchmark(model):    
    # Initialize the base conversation array with the system instruction
    conversation_history = [
        {"role": "system", "content": "You are a concise assistant. Provide answers under 15 words."}
    ]
    
    # Define a sequence of user prompts that build a continuous conversation
    user_turns = [
        "Hi, I am planning a weekend trip to Paris.",          # Turn 1: Cold start for system + prompt
        "What are the top two places I must visit there?",     # Turn 2: Cache hit for Turn 1
        "Can you suggest a good local food to try there?",     # Turn 3: Cache hit for Turns 1 & 2
        "How do I say 'Thank you' in their language?"          # Turn 4: Cache hit for Turns 1, 2 & 3
    ]
    
    execution_times = []

    print("\n💬 Starting Evolving Multi-Turn Conversation...")

    for i, user_input in enumerate(user_turns, start=1):
        # Append the new user turn to our growing history list
        conversation_history.append({"role": "user", "content": user_input})
        
        print(f"\n▶️ [TURN {i}] User: '{user_input}'")
        
        start = time.perf_counter()
        response = model.create_chat_completion(
            messages=conversation_history, 
            max_tokens=50, 
            temperature=0.7
        )
        elapsed_time = time.perf_counter() - start
        execution_times.append(elapsed_time)
        
        # Extract the actual textual response generated by the model
        assistant_text = response["choices"][0]["message"]["content"].strip()
        print(f"🤖 Assistant: {assistant_text}")
        
        # Append the model's exact response back into history so the prefix matches perfectly next turn
        conversation_history.append({"role": "assistant", "content": assistant_text})
        
    return execution_times

if __name__ == "__main__":
    gguf_file = Path("F:/gguf/model_q4_k_m.gguf")
    
    print("📦 Building Model Instance ...")
    model = Llama(model_path=str(gguf_file), n_ctx=8192, n_gpu_layers=-1, verbose=True)

    times = run_evolving_history_benchmark(model)
    print("\n📊 ROLLING PROMPT CACHE PERFORMANCE ANALYSIS:")
    print(f" • Turn 1 (Cold Start):  {times[0]:.4f}s")
    print(f" • Turn 2 (Cache Hit):  {times[1]:.4f}s")
    print(f" • Turn 3 (Cache Hit):  {times[2]:.4f}s")
    print(f" • Turn 4 (Cache Hit):  {times[3]:.4f}s")
    
    # Calculate relative speedups relative to the initial ingest time
    for idx, t_val in enumerate(times[1:], start=2):
        speedup = ((times[0] - t_val) / times[0]) * 100
        print(f" ⚡ Turn {idx} was {speedup:.1f}% faster than Turn 1.")

    print("\n🏁 Multi-turn session complete.")
